
server:
  port : 8081 
spring:
  datasource:
    username : root 
    password :
    url : jdbc:mysql://localhost:3306/order_database?serverTimezone=UTC
   
    
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect 
        ddl-auto : update
    
eureka:
  instance:
    instanceId :  ${spring.application.name}:${server.port} 
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
      
      
info:
  app:
    name : orders-service
    description : order prgocessin service to fetch order details.
      
      